project:
  type: website

resources:
  - "/index.html"
  - "/matteo_pedani/matteo.pedani.vcf"
profile:
  default: italian
  group: [english, italian]

#format:
#  html:
#    header-includes: '<link rel="preconnect" href="https://fonts.googleapis.com"> <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> <link href="https://fonts.googleapis.com/css2?family=Chango&display=swap" rel="stylesheet">' 