---
title: "Nocerosso srl"
---
## Sistema integrato di allevamento di pesci e ostriche in mare aperto e lagunare con l'istallazione contemporanea di pannelli fotovoltaici e generatori elettrici dalle onde con delle  boe 


Il sistema integrato per la produzione ittica e di ostriche in alto mare e nelle lagune di Oristano prevede l'impiego di campi di boe "point absorber" e pannelli fotovoltaici galleggianti per la produzione di energia elettrica. L'utilizzo congiunto di tali tecnologie, insieme all'allevamento ittico e alle ostriche, comporta numerosi vantaggi.

### I vantaggi del sistema integrato

Uno dei maggiori vantaggi di questo sistema integrato è l'impiego cointemporaneo della stessa manodopera per il controllo dei campi di boe e pannelli solari e per l'allevamento ittico e delle ostriche, che porta ad un aumento della resa per unità lavorativa. Ciò significa che i lavoratori possono controllare sia le attività di coltivazione che la produzione di energia elettrica, senza dover dividere il loro tempo tra due attività separate.


---
